### ISSUE TITLE
another possible region algorithm?

### ISSUE THREAD

**Issue by jcupitt** [lovell/attention#8]
Here's an interesting alternative smart crop algorithm:

http://stackoverflow.com/a/1517178/894763

The idea is that smart crop is generally used to reduce portrait or landscape pictures to squares, since you can then show a large grid of images of varying aspect ratios in a sensible way. 

So this algorithm does not attempt to find the interesting parts of the image and frame them nicely, which is very difficult, but just to remove the most boring parts from the ends of the longest axis. It finds boringness by estimating image entropy from the histogram.

Here it is in Python with libvips:

https://gist.github.com/jcupitt/c2792a9b22e4e2544147

Original thread:

https://github.com/jcupitt/libvips/issues/317

**Comment by lovell** [comment]
Thanks again John, this approach should be much faster when "squaring-off" a rectangle.

There are some recent additions to libjpeg-turbo that allow you to decode scanline ranges rather than the whole image, which should improve the speed for portrait images.

I've also had ideas involving the new entropy calculation feature of libvips around adaptive compression levels.

**Comment by lovell** [comment]
Entropy-based crop is available in sharp v0.14.0+ http://sharp.dimens.io/en/stable/changelog/#v0140-2nd-april-2016
